### ISSUE TITLE
集成好了编译通过，运行时直接闪退,防混淆也加了，就是找不到属性UMConfigure中的umDebugLog 

### ISSUE THREAD

**Issue by helloxiaohui** [umeng/MultiFunctionAndroidDemo#11]
05-29 09:07:35.544 18979-19129/? E/AndroidRuntime: FATAL EXCEPTION: Thread-9351
                                                   Process: com.xxxxx, PID: 18979
                                                   java.lang.NoSuchFieldError: No static field umDebugLog of type Lcom/umeng/commonsdk/debug/UMDebugLog; in class Lcom/umeng/commonsdk/UMConfigure; or its superclasses (declaration of 'com.umeng.commonsdk.UMConfigure' appears in /data/app/com.xxxx-2/split_lib_dependencies_apk.apk)
                                                       at com.umeng.socialize.utils.SLog.E(SLog.java:32)
                                                       at com.umeng.socialize.UMShareAPI$a.a(UMShareAPI.java:349)
                                                       at com.umeng.socialize.UMShareAPI$a.doInBackground(UMShareAPI.java:328)
                                                       at com.umeng.socialize.common.QueuedWork$UMAsyncTask$1.run(QueuedWork.java:136)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by KomoriWu** [comment]
同样遇到了，解决了吗

**Comment by chenyusheng** [comment]
这可能是umeng的share版本跟common版本不一致
