### ISSUE TITLE
Twitter 授权授权用户信息 删除

### ISSUE THREAD

**Issue by SilasDong** [umeng/MultiFunctionAndroidDemo#12]
06-04 18:20:12.380 25696-25910/com.android.xinchidao.xxoogo E/CrashHandler: In thread: Thread[Thread-26,5,main]
    UncaughtException detected: java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
        at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:192)
        at twitter4j.TwitterImpl.get(TwitterImpl.java:199)
        at twitter4j.TwitterImpl.showUser(TwitterImpl.java:163)
        at com.umeng.socialize.handler.TwitterHandler$SaveDateThread.run(TwitterHandler.java:174)
        at java.lang.Thread.run(Thread.java:761)
06-04 18:20:12.381 25696-25910/com.android.xinchidao.xxoogo E/AndroidRuntime: FATAL EXCEPTION: Thread-26
    Process: com.android.xinchidao.xxoogo, PID: 25696
    java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
        at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:192)
        at twitter4j.TwitterImpl.get(TwitterImpl.java:199)
        at twitter4j.TwitterImpl.showUser(TwitterImpl.java:163)
        at com.umeng.socialize.handler.TwitterHandler$SaveDateThread.run(TwitterHandler.java:174)
        at java.lang.Thread.run(Thread.java:761)

**Comment by jingchangfa** [comment]
哥们你可以用么？我这边twitter授权登录，几个回调都不走。配置也没问题。。qq 微信 微博 Facebook 都可以正常使用。。。唯独twitter有问题～～
