### ISSUE TITLE
 couldn't find "libumeng-spy.so" 这个是什么原因

### ISSUE THREAD

**Issue by hawskpy** [umeng/MultiFunctionAndroidDemo#75]
2020-10-29 14:51:37.493 28635-28635/com.zerotech.gstaion.test W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zerotech.gstaion.test-K8igH-scRFBOzbJunBCq6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.zerotech.gstaion.test-K8igH-scRFBOzbJunBCq6A==/lib/arm, /data/app/com.zerotech.gstaion.test-K8igH-scRFBOzbJunBCq6A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libumeng-spy.so"
2020-10-29 14:51:37.494 28635-28635/com.zerotech.gstaion.test W/System.err:     at com.umeng.umzid.Spy.<clinit>(Spy.java:7)
2020-10-29 14:51:37.494 28635-28635/com.zerotech.gstaion.test W/System.err:     at com.umeng.commonsdk.UMConfigure.getClass(UMConfigure.java:95)
2020-10-29 14:51:37.494 28635-28635/com.zerotech.gstaion.test W/System.err:     at com.umeng.commonsdk.UMConfigure.init(UMConfigure.java:537)

你们umeng 还集成一个间谍.so 吗？ 哈哈~

**Comment by hawskpy** [comment]
太坑了！！
从这个链接下载的统计SDK
https://developer.umeng.com/sdk?spm=a211g2.181323.0.0.3cb23604tEu8I2
尽然没有.so库
