### ISSUE TITLE
新浪微博包少东西吧？

### ISSUE THREAD

**Issue by leadersm** [umeng/MultiFunctionAndroidDemo#80]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sina/weibo/sdk/auth/AuthInfo;
        at com.umeng.socialize.handler.SinaSsoHandler.onCreate(SinaSsoHandler.java:95)
        at com.umeng.socialize.a.a.b(SocialRouter.java:328)
        at com.umeng.socialize.UMShareAPI$4.doInBackground(UMShareAPI.java:236)
        at com.umeng.socialize.common.QueuedWork$UMAsyncTask$1.run(QueuedWork.java:136)

**Comment by yueqianzhang** [comment]
新浪微博SDK需要自行集成
